name: Publish Python ðŸ distribution ðŸ“¦ to PyPI and TestPyPI

on: push
jobs:
  build:
    name: Build distribution ðŸ“¦
    runs-on: ubuntu-latest

    steps:
      # sdsdad
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # ddddd
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # dddddd
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      # eeee
      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      #
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
